=head1 DESCRIPTION

Net::OpenStack::Compute provides Perl bindings for the OpenStack Compute API.
It also provides a command line tool C<oscompute> for interacting with a
OpenStack deployment.
See 
L<Net::OpenStack::Compute|https://metacpan.org/module/Net::OpenStack::Compute>
for documentation.

=head1 INSTALLATION

    sudo cpanm Net::OpenStack::Compute

or

    sudo cpanm oscompute

or

    curl -L cpanmin.us | perl - --sudo Net::OpenStack::Compute

or

    sudo cpan Net::OpenStack::Compute

To install from a local git checkout, cd to the project directory and run:

    sudo cpanm .

If you do not have cpanm, you can install it via:

    curl -L cpanmin.us | perl - --sudo cpanm

=head1 DOCUMENTATION

See 
L<Net::OpenStack::Compute|https://metacpan.org/module/Net::OpenStack::Compute>
